write_files() {
    print_step "Creating Vaanee directory at $VAANEE_DIR"
    mkdir -p "$VAANEE_DIR"
    cd "$VAANEE_DIR"

    # ── Detect if this is a Neon DB URL and add required SNI parameter ──
    # Neon serverless Postgres requires options=endpoint%3D<endpoint-id> in the
    # connection string for SNI routing. Without it, psycopg2 (Python) fails to
    # connect silently, causing flow definitions to not load during calls.
    DB_URL_FOR_ENV="$DATABASE_URL"
    if echo "$DATABASE_URL" | grep -q "neon.tech"; then
        # Extract endpoint ID from the hostname (format: ep-xxx-yyy.region.aws.neon.tech)
        NEON_ENDPOINT=$(echo "$DATABASE_URL" | grep -oP 'ep-[a-z0-9-]+(?=\.[a-z0-9-]+\.aws\.neon\.tech)')
        if [ -n "$NEON_ENDPOINT" ] && ! echo "$DATABASE_URL" | grep -q "options=endpoint"; then
            # Append the SNI endpoint parameter
            if echo "$DATABASE_URL" | grep -q "?"; then
                DB_URL_FOR_ENV="${DATABASE_URL}&options=endpoint%3D${NEON_ENDPOINT}"
            else
                DB_URL_FOR_ENV="${DATABASE_URL}?options=endpoint%3D${NEON_ENDPOINT}"
            fi
            print_success "Neon DB detected — added SNI endpoint parameter for psycopg2 compatibility"
        fi
    fi

    # Add query params safely: use ? for first parameter, & for additional ones
    DB_URL_DELIM="?"
    if echo "$DB_URL_FOR_ENV" | grep -q "?"; then
        DB_URL_DELIM="&"
    fi

    # ── .env ──────────────────────────────────────────────
    cat > .env << EOF
# Vaanee On-Premise Configuration
# Generated by installer on $(date)

# ── Licence ──────────────────────────────────────────────
VAANEE_API_KEY=$VAANEE_API_KEY
INSTANCE_ID=$(hostname)-$(openssl rand -hex 4)

# ── Database ─────────────────────────────────────────────
# NOTE: keepalives params keep long-lived connections alive (important for voice calls)
# NOTE: options=endpoint%3D is required for Neon DB SNI routing (psycopg2 compatibility)
DATABASE_URL=${DB_URL_FOR_ENV}${DB_URL_DELIM}keepalives=1&keepalives_idle=30&keepalives_interval=10&keepalives_count=5&connect_timeout=10

# ── App ──────────────────────────────────────────────────
NODE_ENV=production
PORT=8080
VAANEE_MODE=true

# ── Security ─────────────────────────────────────────────
JWT_SECRET=$JWT_SECRET
ENCRYPTION_MASTER_KEY=$ENCRYPTION_MASTER_KEY
ENCRYPTION_SECRET=$ENCRYPTION_SECRET

# ── Frontend ─────────────────────────────────────────────
NEXT_PUBLIC_API_URL=https://$VAANEE_DOMAIN
NEXT_PUBLIC_BACKEND_URL=https://$VAANEE_DOMAIN
NEXT_PUBLIC_CALLER_AI_BASE_URL=https://$VAANEE_DOMAIN
NEXT_PUBLIC_SEO_BACKEND_URL=https://$VAANEE_DOMAIN
NEXT_PUBLIC_PLATFORM_NAME=Vaanee
NEXT_PUBLIC_MAIN_APP_URL=https://$VAANEE_DOMAIN
NEXT_PUBLIC_VAANEE_MODE=true

# ── Domain ───────────────────────────────────────────────
VAANEE_DOMAIN=$VAANEE_DOMAIN
ADMIN_EMAIL=$ADMIN_EMAIL

# ── Webhook internal API ─────────────────────────────────
INTERNAL_API_URL=http://vaanee-backend:8080
PUBLIC_BASE_URL=https://$VAANEE_DOMAIN
INBOTIQ_API=$INBOTIQ_API
EOF

    print_success ".env created"

    # ── Caddyfile ─────────────────────────────────────────
    cat > Caddyfile << EOF
$VAANEE_DOMAIN {
    tls $ADMIN_EMAIL

    handle /api/login {
        reverse_proxy vaanee-frontend:8080
    }

    handle /api/auth/* {
        reverse_proxy vaanee-frontend:8080
    }

    handle /api/* {
        reverse_proxy vaanee-backend:8080
    }

    handle /exotel/* {
        reverse_proxy vaanee-webhook:8000 {
            header_up Host {host}
            header_up X-Forwarded-Proto {scheme}
            header_up X-Forwarded-Host {host}
        }
    }

    handle /flow/* {
        reverse_proxy vaanee-webhook:8000 {
            header_up Host {host}
            header_up X-Forwarded-Proto {scheme}
            header_up X-Forwarded-Host {host}
        }
    }

    handle /answer {
        reverse_proxy vaanee-webhook:8000 {
            header_up Host {host}
            header_up X-Forwarded-Proto {scheme}
        }
    }

    handle /calls {
        reverse_proxy vaanee-webhook:8000 {
            header_up Host {host}
            header_up X-Forwarded-Proto {scheme}
        }
    }

    handle /webhook/* {
        reverse_proxy vaanee-webhook:8000
    }

    handle /health {
        reverse_proxy vaanee-backend:8080
    }

    handle {
        reverse_proxy vaanee-frontend:8080
    }
}
EOF

    print_success "Caddyfile created"

    # ── docker-compose.yml ────────────────────────────────
    # IMPORTANT: Do NOT hardcode DATABASE_URL in the webhook environment section.
    # The webhook container must read DATABASE_URL from .env (via env_file) so
    # that the Neon SNI parameter and keepalives are included. Hardcoding it in
    # the environment: block overrides .env and loses these critical parameters,
    # causing the flow definition DB lookup to fail silently during calls.
    cat > docker-compose.yml << EOF
networks:
  vaanee-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:

services:
  caddy:
    image: caddy:2-alpine
    container_name: vaanee-caddy
    restart: unless-stopped
    networks:
      - vaanee-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - vaanee-frontend
      - vaanee-backend
      - vaanee-webhook

  vaanee-backend:
    image: $REGISTRY/vaanee-backend:qa
    container_name: vaanee-backend
    restart: unless-stopped
    networks:
      - vaanee-network
    env_file:
      - .env
    environment:
      - N8N_CALLER_AI_WEBHOOK_URL=https://$VAANEE_DOMAIN/exotel/calls
      - AI_WEBHOOK_BASE_URL=https://$VAANEE_DOMAIN
      - CALLER_AI_CAMPAIGN_ENDPOINT_URL=https://$VAANEE_DOMAIN/exotel/campaigns
      - N8N_CALLER_AI_FIRST_MESSAGE_WEBHOOK_URL=https://$VAANEE_DOMAIN/exotel/answer

  vaanee-webhook:
    image: $REGISTRY/vaanee-webhook:qa
    container_name: vaanee-webhook
    restart: unless-stopped
    networks:
      - vaanee-network
    env_file:
      - .env
    environment:
      - CALL_WEBSOCKET_URL=wss://$VAANEE_DOMAIN/exotel/ws
      - WEBSOCKET_URL_HOST=$VAANEE_DOMAIN
      - WEBSOCKET_URL_SCHEME=wss
      - WEBSOCKET_URL_PATH=/exotel/ws
      # DATABASE_URL is intentionally NOT set here — it comes from .env above
      # so that the Neon SNI parameter and keepalives are preserved.

  vaanee-checkin:
    image: $REGISTRY/vaanee-webhook:qa
    container_name: vaanee-checkin
    restart: unless-stopped
    networks:
      - vaanee-network
    env_file:
      - .env
    command: ["python", "checkin_service.py"]

  vaanee-frontend:
    image: $REGISTRY/vaanee-frontend:qa
    container_name: vaanee-frontend
    restart: unless-stopped
    networks:
      - vaanee-network
    env_file:
      - .env
    depends_on:
      - vaanee-backend
      - vaanee-webhook
EOF

    print_success "docker-compose.yml created"

    # Download migration SQL bundle (master + parts)
    mkdir -p migrations
    curl -fsSL https://raw.githubusercontent.com/Inbotiq-com/vaanee-install/main/migrate.sql -o migrate.sql
    curl -fsSL https://raw.githubusercontent.com/Inbotiq-com/vaanee-install/main/migrations/001_extensions.sql -o migrations/001_extensions.sql
    curl -fsSL https://raw.githubusercontent.com/Inbotiq-com/vaanee-install/main/migrations/002_agents_and_flows.sql -o migrations/002_agents_and_flows.sql
    curl -fsSL https://raw.githubusercontent.com/Inbotiq-com/vaanee-install/main/migrations/003_knowledge_base.sql -o migrations/003_knowledge_base.sql
    curl -fsSL https://raw.githubusercontent.com/Inbotiq-com/vaanee-install/main/migrations/004_calls_runtime.sql -o migrations/004_calls_runtime.sql
    curl -fsSL https://raw.githubusercontent.com/Inbotiq-com/vaanee-install/main/migrations/005_pronunciation_and_campaigns.sql -o migrations/005_pronunciation_and_campaigns.sql
    curl -fsSL https://raw.githubusercontent.com/Inbotiq-com/vaanee-install/main/migrations/006_indexes_and_finalize.sql -o migrations/006_indexes_and_finalize.sql
    print_success "Migration bundle downloaded"
}

# ============================================================
# 7b. Run database migrations
# ============================================================
run_migrations() {
    print_step "Running database migrations"

    if ! command -v psql &>/dev/null; then
        print_warn "Installing PostgreSQL client..."
        sudo apt-get install -y -qq postgresql-client 2>/dev/null || \
        sudo apt-get install -y -qq postgresql-client-14 2>/dev/null || \
        sudo apt-get install -y -qq postgresql-client-16 2>/dev/null || true
    fi

    if command -v psql &>/dev/null; then
        print_step "Validating PostgreSQL pgvector support"
        if psql "$DATABASE_URL" -tAc "SELECT 1 FROM pg_available_extensions WHERE name='vector';" | grep -q "1"; then
            print_success "pgvector extension is available"
        else
            print_error "pgvector extension is not available on this PostgreSQL instance."
            echo "  Please install/enable pgvector on your database server, then rerun installer."
            exit 1
        fi

        if psql "$DATABASE_URL" -f "$VAANEE_DIR/migrate.sql" -v ON_ERROR_STOP=1; then
            print_success "Database migrations completed"
        else
            print_error "Database migration failed. Fix SQL errors and rerun installer."
            exit 1
        fi
    else
        print_warn "psql not available — skipping auto migration."
        echo ""
        echo "  Run migrations manually before starting Vaanee:"
        echo "    psql \"$DATABASE_URL\" -f $VAANEE_DIR/migrate.sql"
        echo ""
    fi
}

# ============================================================
# 8. Login to registry and pull images
# ============================================================
